### ISSUE TITLE
DB-Manager sends Errors and Warnings via Messenger or Email

### ISSUE THREAD

**Issue by LeeLux** [Jon-Kle/DB-Manager#8]
The Idee is that the program can send Messages (Infos, Warnings, Errors etc.) via Signal, Telegram or WhatsApp Messanger or Email.
A Messanger would be nicer because an Admin could go the the program and tell it to add a new tel. number to a group with a bot that sends the Messages. This way you can "subscribe" to it. Also this way you could add an remote control to the program and debugger.

**Comment by Jon-Kle** [comment]
I created a milestone for this. Maybe you want to close this issue and modify the milestone as you like.
If you start the development of this, you can add issues to it, that describe small chunks of work to get closer to this goal.

**Comment by Jon-Kle** [comment]
I did some more research, and it turns out, a mail system is not as complicated as i initially thought. The program just needs a main address and a password. And it can send E-Mails as this Account.
I found a [Video](https://youtu.be/B1IsCbXp0uE) that explains this with gmail, but i would like to use web.de for this purpose.
How that works is explained [here](https://draeger-it.blog/senden-einer-e-mail-aus-einem-python3-skript/).  
  
What you @LeeLux could do if you have time is, you could write a python program in an extra file as a module, that sends E-Mails:
- Just create a new branch and add the file to the src folder
- Do some research on how modules in python work. Especially about `if __name__ == '__main__':`
- You can create a test account at web.de for this purpose.
- Please write all sensitive data (the Account E-Mail, the Account Password, the E-Mail addresses the messages get sent to and so on) in a separate json file and encrypt it with `git secret` before you push it to Github!
- (And please don't use so many nested functions)
- If the first version is done and works, you can add custom messages for the different errors that can occur while the request timer is running.
  
If you have any questions, just ask or see if you can find help on the internet. Also you don't have to rush it, take your time.  
This is a bigger project, so maybe use the Milestone to gather smaller tasks as issues.

**Comment by Jon-Kle** [comment]
Ah, and don't forget to update the branch you want to work on to the newest code in the main branch before starting to work on it, so the merging later is not as complicated.
